// Code generated by go-swagger; DO NOT EDIT.

package record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/t1cg/VL/api/backend/models"
)

// GetRecordOKCode is the HTTP code returned for type GetRecordOK
const GetRecordOKCode int = 200

/*GetRecordOK Data based on parameters

swagger:response getRecordOK
*/
type GetRecordOK struct {

	/*
	  In: Body
	*/
	Payload *models.Record `json:"body,omitempty"`
}

// NewGetRecordOK creates GetRecordOK with default headers values
func NewGetRecordOK() *GetRecordOK {

	return &GetRecordOK{}
}

// WithPayload adds the payload to the get record o k response
func (o *GetRecordOK) WithPayload(payload *models.Record) *GetRecordOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get record o k response
func (o *GetRecordOK) SetPayload(payload *models.Record) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRecordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRecordInternalServerErrorCode is the HTTP code returned for type GetRecordInternalServerError
const GetRecordInternalServerErrorCode int = 500

/*GetRecordInternalServerError Internal server error

swagger:response getRecordInternalServerError
*/
type GetRecordInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewGetRecordInternalServerError creates GetRecordInternalServerError with default headers values
func NewGetRecordInternalServerError() *GetRecordInternalServerError {

	return &GetRecordInternalServerError{}
}

// WithPayload adds the payload to the get record internal server error response
func (o *GetRecordInternalServerError) WithPayload(payload *models.ReturnCode) *GetRecordInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get record internal server error response
func (o *GetRecordInternalServerError) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRecordInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetRecordDefault Subscribe service unexpected error response

swagger:response getRecordDefault
*/
type GetRecordDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewGetRecordDefault creates GetRecordDefault with default headers values
func NewGetRecordDefault(code int) *GetRecordDefault {
	if code <= 0 {
		code = 500
	}

	return &GetRecordDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get record default response
func (o *GetRecordDefault) WithStatusCode(code int) *GetRecordDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get record default response
func (o *GetRecordDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get record default response
func (o *GetRecordDefault) WithPayload(payload *models.ReturnCode) *GetRecordDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get record default response
func (o *GetRecordDefault) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRecordDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
