// Code generated by go-swagger; DO NOT EDIT.

package record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRecordHandlerFunc turns a function with the right signature into a get record handler
type GetRecordHandlerFunc func(GetRecordParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRecordHandlerFunc) Handle(params GetRecordParams) middleware.Responder {
	return fn(params)
}

// GetRecordHandler interface for that can handle valid get record params
type GetRecordHandler interface {
	Handle(GetRecordParams) middleware.Responder
}

// NewGetRecord creates a new http.Handler for the get record operation
func NewGetRecord(ctx *middleware.Context, handler GetRecordHandler) *GetRecord {
	return &GetRecord{Context: ctx, Handler: handler}
}

/* GetRecord swagger:route GET /record record getRecord

Single record details

Returns the details of a single record with a matching id

*/
type GetRecord struct {
	Context *middleware.Context
	Handler GetRecordHandler
}

func (o *GetRecord) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRecordParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
