// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Medicare API
//
//  API used to get medicare data
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /go/api
//  Version: 0.0.1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
