export const RECORDS_SUBMIT = 'RECORDS_SUBMIT';
export const RECORDS_INPUT_CHANGE = 'RECORDS_INPUT_CHANGE';
export const RECORDS_STORE = 'RECORDS_STORE';
export const RECORDS_RESET = 'RECORDS_RESET';
export const RECORD_SUBMIT = 'RECORD_SUBMIT';
export const SINGLE_RECORD = 'SINGLE_RECORD';
export const RECORD_ERROR = 'RECORD_ERROR'; 