export const REGISTER_INPUT_CHANGE = 'REGISTER_INPUT_CHANGE';
export const REGISTER_SUBMIT = 'REGISTER_SUBMIT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_RESET = 'REGISTER_RESET';