// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Register register
//
// swagger:model Register
type Register struct {

	// email
	// Required: true
	// Format: email
	Email *strfmt.Email `json:"email"`

	// password1
	// Required: true
	Password1 *string `json:"password1"`

	// password2
	// Required: true
	Password2 *string `json:"password2"`
}

// Validate validates this register
func (m *Register) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword1(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword2(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Register) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	if err := validate.FormatOf("email", "body", "email", m.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Register) validatePassword1(formats strfmt.Registry) error {

	if err := validate.Required("password1", "body", m.Password1); err != nil {
		return err
	}

	return nil
}

func (m *Register) validatePassword2(formats strfmt.Registry) error {

	if err := validate.Required("password2", "body", m.Password2); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this register based on context it is used
func (m *Register) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Register) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Register) UnmarshalBinary(b []byte) error {
	var res Register
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
